

label new_tonks_intro:
    #knock on the office door
    #option to ask who it is
    #bla bla bla, intro stuff
    ton "So, Professor Dumbledore, are you aware why I have been sent here be the Ministry of Magic?"
    m "None at all."
    ton "You haven't had any complaints from students regarding any \"favour trading\"?"
    m "What sort of favours are you talking about?"
    ton "..."
    ton "In any case, I think it would be best that we bring the student in question up here to answer a few questions and hopefully clear everything up."
    ton "Are you acquainted with a Hermione Granger."
    m "We've met."
    ton "Fantastic. Would you mind summoning up here for me?"
    m "Certainly."
    ">With that, you summon the trouble making Miss Granger up to your office."
    her "Oh, hello Tonks! What are you doing here?"
    m "You two know each other?"
    her "Of course! We're all members of the order of the phoenix!."
    ton "Don't talk about that!"
    her "What? Why? Are you worried about he-who-must-not-be-named?"
    ton "Worse... continuity..."
    her "?"
    ton "Anyway, I'm here today to address some concerns students brought to the ministry."
    ton "Specifically, you're letter describing an \"unjust\" favour trading ring taking place at Hogwarts."
    her "Oh! The letter!"
    her "I didn't actually think anyone would read it..."
    ton "Now, now, have some faith in the ministry Miss Granger."
    her "You're right."
    ton "Now, would you be able to tell me a little about the sort of favours that are happening?"
    her "Oh... of course! What would you like to hear first?"
    ton "In your mention, you mentioned the slytherin house were the main offenders..."
    her "The slytherin sluts! Where do I begin?"
    her "There's the time Tracey Davis gave slughorn a lapdance in the middle of class."
    ton "In the middle of class?"
    her "Well, she was just sitting on his lap while he taught from his desk..."
    her "But we could all see her shaking her hips!"
    ton "Interesting... Any other incidents?"
    her "More than I can count!"
    her "Pansy Parkinson will let Snape grab her ass whenever he wants for 5 points a pop!"
    ton "Points? Is that how every one is being paid?"
    her "Of course! I've even heard that Slughorn will hold makeout competitions in his office after dark where the winner gets a hundred!"
    ton "So there's no gold involved?"
    her "I don't think so..."
    ton "Interesting... Please, go on. You mentioned something about girls making out?"
    her "I wish that was the worst of it!"
    ton "Ugh... go on..."
    her "I think a few girls might even be going all the way..."
    ton "really? Just for a few points?"
    her "Yep! From what I heard, Viola Richmond has sex with any teacher she can!"
    her "There are rumors that she's even done it with some of the female teachers..."
    ton "Wow... That's... pretty crazy..."
    ton "So... What's the problem?"
    her "What's the problem?!"
    her "The problem is that it's unfair to the boys!"
    ton "What?"
    her "Ugh... I knew you ministry goons wouldn't bother reading my letter properly!"
    her "Did you even read about the plights of the M.R.M., the \"men's rights movement\"?"
    ton "Wait... You're problem isn't that the girls of this school are engaging in illicit, sexual favours with their teachers..."
    ton "It's that the boys aren't able to do the same?"
    her "Exactly!"
    her "I don't want to stop the favour trading..."
    her "(I don't think gryffindor could win if we did that.)"
    her "I just want to make it fair, so that everyone can participate."
    ton "You want to make sex favours... fair..."
    her "Of course! They're so much fun, I don't think it makes sense to stop them..."
    ton "Wait... are you trading favours?"
    her "Oh... umm... I wasn't when I sent the letter, I promise!"
    ton "But you are now?"
    her "Ummm... maybe?"
    her "That's not a problem is it?"
    ton "Not if you're happy to do it... I'm hardly the moral police."
    m "Aren't you the magic police though?"
    ton "It's a bit of a grey area. I don't think this really counts as a magical crime..."
    ton "But I was assigned to investigate and resolve this issue..."
    her "Oh... so you are going to shut it down?"
    her "Well, if you do, make sure you take aways all the dirty points that slytherin managed to get their grimy hands on!"
    ton "Now, now, now... I never said I'd shut down your naughty little favour trading game..."
    ton "From what I can tell, all you need is another player."
    her "Another player?"
    ton "From what you were saying, apparently the problem is that the boys don't have anyone to sell favours to..."
    ton "But if a new teacher should come along... One that's happy to purchase favours from all her willing students..."
    ton "Well, I think that solves everyone's problems... Don't you?"
    her "You mean... You'd start buying favours from the boys?"
    m "I'm not so sure-"
    her "It's perfect! I hadn't even considered this solution to the M.R.M.s problems!"
    ton "You think so?"
    her "Of course! This way it's finally an even playing field for everyone!"
    her "So long as you don't buy too many points from those dirty slytherins!"
    ton "I still have to become a teacher first..."
    ton "So what do you say, Dumbledore? Any vacancies you need filled?"
    m "Hold on a second... Aren't you here to investigate the school? Why are you suddenly asking for a job?"
    ton "Well, I've only just started this job but my new title is technically \"Auror in charge of Hogwarts protection and oversight\"..."
    ton "So I think I'm allowed to stay on as a teacher while I work. At least that's how Mad Eye Moody did it when he was overseeing the goblet of fire."
    ton "Or was that the death-eater, Barty Crouch Jr in disguise?..."
    ton "Either way, there's a precedent for it."
    m "(I have no idea who or what she was just talking about.)"
    ton "Or, I could just bring this whole thing to the attention of the ministry and let them deal with it."
    ton "I'm sure that they'll love to hear you've all been shagging your students senseless..."
    m "Welcome aboard Miss- um..."
    ton "It's Tonks, Dumbledore. Surely you remember me from when I was a student."
    ton "God knows I was sent to this office often enough."
    m "Of course, I was just unsure of your title these days..."
    ton "(Title?)"
    m "You can take whatever position is vacant."
    #Have her become a teacher, send Hermione off and discuss how she's going to start seducing her students with Dumbledore
