#Favour 3 - Kiss me (Tonks makes-out with her students)
label tonks_teacher_event_3_intro: #First intro
    m "Ready to try something a little different?"
    ton "Mmmm, you bet... This is the most fun I've had in years!"
    ton "What were you thinking we try out next?"
    m "What do you think?"
    ton "I know you shot it down earlier... but I think making-out with them would be really fucking hot..."
    m "Pfft, you're such a girl."
    m "You've already gotten to second base, let's not jump back to first!"
    ton "You don't understand... The way I make-out... It's way more intense than anything these kids will have ever experienced..."
    m "Hmmmm... So you're not just going to give them a peck on the cheek, are you?"
    ton "Oh no..."
    ton "They'll be lucky if they can talk straight after I'm done with them..."
    m "In that case, you have my permission..."
    m "Just don't disappoint me with the stories you bring back!"
    ton "I'll make sure you get your money's worth, don't worry."
    m "Just see me after class."
    ton "Yes, sir!"


    return

label tonks_teacher_event_3_repeat: #Repeatable intro
    m "Fancy another student-snog-session?"
    ton "Mmmm, you bet... It's my job to teach these kids..."
    ton "Even if that lesson is French Kissing..."
    m "Well, don't let me stop you."
    ton "Thank you, sir..."

    return

label tonks_teacher_event_3_1: #Level 1 Event 1
    m "How did your extra-curricular activities pan out today?"
    ton "Honestly? I don't think I've ever been as turned on in my life..."
    ton "Fuck... It was incredible... the power I felt over him... it was intoxicating..."
    m "Care to elaborate?"
    ton "Well, you know that stuck up little \"Slytherin\" I've been fooling around with?"
    m "The guy or the girl?"
    ton "The boy."
    m "Yep, I think I remember them..."
    ton "I asked them to stay back after classes again... Even if it was by staring at them during class..."
    ton "Either way... He knew he had to stay behind to play with \'auntie\' tonks..."
    m "Kinky..."
    ton "Mmmm, I walked over to him slowly... Making sure I savored that frightened look on his face..."
    ton "Then, I got to his desk... I was half expecting him to blabber on about not deserving to be there..."
    ton "But today he just looked up at me with a delectable mix of fear and anticipation..."
    ">Unable to help yourself any longer, you start to inconspicuously stroke your cock under your desk."
    ton "...{w}*tsk*tsk*tsk*{w}Couldn't help yourself, could you?"
    m "Can you blame me?"
    ton "I suppose not..."
    ton "Anyway, back to that cute little thing..."
    ton "Eventually I'd had enough of his eager expression..."
    ton "I pounced upon him... Sitting down on his lap, pinning him to his chair and forcing my chest into his..."
    ton "I could feel his heartbeat... It so fast... Like a mouse..."
    ton "Whispering in his ear I made sure I asked if he wanted a little kiss..."
    ton "Letting him know I'd pay him plenty of points..."
    ton "Just for a kiss..."
    m "Mmmmm..."
    ton "Of course he said yes... Even if it was so faint I could barely hear it..."
    ton "But once he said it... I was on him..."
    ton "I pinned him down as I held his head in place..."
    ton "Ugh... My tongue was going crazy..."
    ton "I'm not sure if you remember this from school, sir, but I'm an Metamorphmagus..."
    ton "Normally I just use that to blend in or for jokes..."
    ton "But sometimes I use it to... Play around..."
    ton "And all the excitement today may have caused me to lose control of my tongue..."
    m "Lose control of your tongue?"
    ton "Ugh... it was so long..."
    ton "It was like I was fucking that poor boys mouth with it..."
    ton "I wrapped his tongue in mine... stuck it down his throat..."
    ton "Ugh... I even licked his face clean..."
    ton "By the time I was done there wasn't a dry spot on his face..."
    m "Argh..."
    ton "Poor thing... I think I broke him if I'm being honest..."
    m "That's it..."
    ton "I thought he'd like it... but there were so many tears-"
    g9 "UGH... THERE IT IS!!!"
    ">You begin firing a load of under your desk, making a dull thud with each blast hitting against the backboard..."
    ton "Mmmm, looks like you enjoyed our little lesson as well..."
    m "Ugh... can you blame me? That was... Ugh..."
    ton "I told you I knew how to kiss..."
    m "I believe you... that'll be all for now..."
    m "I need to clean up..."
    ton "Very well... Thank you, sir."

    return

label tonks_teacher_event_3_2: #Level 1 Event 2
    m "You're a bit late... Get caught up having fun with your students?"
    ton "Mmmm, and then some..."
    m "I like the sound of that!"
    m "Now, care to elaborate?"
    ton "Alright then, you old perv..."
    ton "Today was that shy, horny \"ravenclaw\" boy..."
    m "The one who stayed behind by himself?"
    ton "Yep..."
    ton "Ugh... he made the classic school boy mistake today..."
    m "Which is?"
    ton "Calling your teacher \'Mommy\'"
    m "hahaha! Really?"
    m "I bet he copped it for that!"
    ton "Surprisingly not... Everyone just sort of went quiet."
    m "Hmmm. I know I would have given him hell for that..."
    ton "Anyway... I decided that was plenty of reason to hold him back..."
    ton "Not that I needed to... Cheeky bugger didn't even get out of his seat..."
    ton "He just sat there with his head down... waiting for me to come over..."
    ton "So, I figured I'd indulge him... I walked over and plonked myself onto his lap, facing towards him..."
    m "Mmmm, did he see that coming."
    ton "No, although it didn't seem to bother him..."
    ton "He just gazed up at me with this look in his eyes..."
    ton "It was too much... I started kissing him just to break our gaze..."
    m "I assume he just sat there, taking it?"
    ton "Oh no... He may have looked shy... but kissing awoke something in him..."
    ton "It was like he wanted to suck my soul out through my mouth... ugh..."
    ton "I've never had attack me with their tongue like that..."
    ton "It was intense... if a little inexperienced..."
    ton "But my god... the most fun I've had in years!"
    m "And what, you made out for a few minutes and sent him on his way?"
    ton "A few minutes? Why do you think I'm so late?"
    m "Wait... You mean to tell me you spent all afternoon, french kissing one of your students?"
    ton "I didn't think it'd-"
    m "I'm very proud. Good work, Tonks."
    ton "..."
    ton "Thank you, Dumbledore."
    return
    
label tonks_teacher_event_3_3: #Level 1 Event 3

    return
    
label tonks_teacher_event_3_4: #Level 1 Event 4

    return
    