#Favour 2 - Touch me (Tonks gets a student to play with her tits)
label tonks_teacher_event_2_intro: #First intro
    m "Ready for the next step?"
    ton "Mmmm, you make it sound so ominous."
    ton "So where do we go from here?"
    ton "Should I start making out with them?"
    m "Pfft, may as well start holding hands."
    m "I was thinking you could take a few of these boys to second base."
    ton "Second base?! Already?"
    m "Obviously. We're trying to earn you a reputation as a favour trader."
    m "Making your students write lines in their underwear isn't going to cut it."
    ton "I suppose you might be right..."
    ton "I'm not sure if the students will be ready for it though..."
    m "Please, you sound like you're talking about a pop-quiz."
    m "All you have to do is follow the damn train-ahem"
    m "All you have to do is get them to grope your chest a little..."
    m "I can't imagine any of them saying no to that."
    m "Goodness knows I wouldn't..."
    ton "Mmm, well if you say so... You are the expert."
    m "That I am. Now get out there and buy some favours!"
    ton "Yes, sir!"
    ton "(This is way better than being an auror!)"
    return

label tonks_teacher_event_2_repeat: #Repeatable intro
    m "Think you're up for messing around with your students again?"
    ton "Mmm, you bet!"
    m "Why don't you let them cop a feel then?"
    ton "Consider it done."
    m "Good to hear. I'll see you after class."
    ton "(I still can't believe Dumbledore is telling me to go molest my students...)"
    ton "Yes, sir!"

label tonks_teacher_event_2_1: #Level 1 Event 1
    m "How were classes today, [tonks_name]?"
    m "Teach your students a valuable lesson?"
    ton "I'm not sure about valuable... But I do know that he isn't going to forget it anytime soon!"
    m "That's what I like to hear! Go on."
    ton "Remember that \'slytherin\' cutie I held back to write lines?"
    m "Vaguely."
    ton "Well, I decided to hold him back after classes again."
    ton "He tried to put on a proud \'slytherin\' facade, Claiming that I had no right to hold him back again."
    ton "Saying he's lucky he didn't report me for making him pull down his pants the first time."
    ton "It was all empty talk though... I could tell by the bulge those pants he wanted to be there more than anything."
    ton "Still, I let him act tough so he wouldn't run away..."
    m "How did you manage to get him to grab a handful then."
    ton "I let him know today wasn't a punishment. I just wanted to talk about him being so distracted in class."
    ton "I sat down next to him and asked what he couldn't stop staring at..."
    ton "He didn't want to say at first, so I leaned in so close my breathe was on his neck..."
    ton "And then whispered in his ear that he was a dirty little tit addict."
    ton "Ugh... he went redder than a tomato when I said that."
    m "No wonder."
    ton "We're not done yet either!"
    ton "Next I told him there was only one cure and grabbed his wrist pulling his hand up to my chest."
    m "Just like that?"
    ton "He was hardly going to grab them himself!"
    ton "Besides, grabbing them is the only way to get them off his mind..."
    ton "Or at least that's what I told him..."
    m "And he believed you?"
    ton "Maybe... Maybe not..."
    ton "All I know is that he wasn't afraid to give it a go."
    m "He enjoyed himself then?"
    ton "Like you wouldn't believe. It was like a kid playing with lego for the first time."
    ton "He just sat there silently playing with them for ten minutes..."
    ton "Ughh... It took everything I had not to hold him down and jump his bones..."
    m "Tonks."
    ton "Right, well after letting him have a play in disneyland for a little while I sent him back to class."
    m "Just like that?"
    ton "There may have been a little more dirty talk... but that's just for me."
    m "Very well... Think you'll gain any rep from this encounter then?"
    ton "Hmmm, I'm not sure if he'll talk... But the fact I keep holding boys behind is starting to spread some rumours by itself."
    m "Good to hear. That'll be all then, [tonk_name]."
    ton "Thank you, Dumbledore."

label tonks_teacher_event_2_2: #Level 1 Event 2

label tonks_teacher_event_2_3: #Level 1 Event 3

label tonks_teacher_event_2_4: #Level 1 Event 4