

### Tonks Teaching ###

#How these favours will be structured/work very similarly to the public favours for Hermione where you send Tonks off to fool around with a student(s) and then wait
#for her to return to tell you what happened
#Each scene will be pretty short but there will be 12 variants for each (4 favours for each of three levels where the levels are determined by Tonk's sluttiness)

#Favour 1 - Show it to me (Tonks gets a student to show her his dick)
label tonks_teacher_event_1_intro: #First time intro
    ton "So, what's the plan?"
    m "The plan?"
    ton "You know, how does this go down?"
    ton "I'm hardly a regular when it comes to this stuff."
    m "Let's start small. We'll need to build up a bit of a reputation for you before you start trying anything crazy."
    ton "A reputation?"
    ton "Think I'll get a nickname? Maybe they'll call me touchy tonks?"
    m "Maybe..."
    ton "So what did you buy off of Hermione on your first favour?"
    m "Ugh... I think I got her to make a silly face or something..."
    m "That and getting her to talk to me."
    ton "Talk to you? You paid her for that? You can get that for free!"
    m "In that case, the first \"real\" favour I bought was getting her to lift her skirt."
    ton "That's more like it!"
    ton "But even though we're in Scotland-"
    m "(we are?)"
    ton "None of the boys are wearing skirts..."
    m "Just get them to show you their dicks then."
    ton "Show me their dicks... That's good... {p}Can I touch them?"
    m "Let's just look for now..."
    ton "Fine... So how many am I allowed to look at?"
    m "As many as you want..."
    ton "And how many points am I allowed to give out?"
    m "Look, I'm not really convinced these points are real..."
    ton "(what? Can't he see the scoreboard at the top of the screen?)"
    m "I just say \"Ten points to gryffindor!\" to get these girls to show me their tits..."
    $ gryffindor += 10
    m "So as far as I'm concerned, hand out as many as you like."
    ton "Alright... Well, I better get to class. I've got some boys to {b}teach{/b}..."
    m "Don't forget to come back here after classes to fill me in."
    ton "Will do..."
    #send tonks off
    return

label tonks_teacher_event_1_repeat: #Repeatable intro
    m "Ready to help the boys earn some points?"
    ton "You mean am I ready to see some dick?"
    m "Is there a difference?"
    ton "There {b}should{/b} be."
    ton "Lucky for you, I'm happy to do both."
    m "See you after classes then."
    ton "Mhmmm... Don't worry if I'm a little late though..."
    ">With that, Tonks strolls out of your office with a hungry look in her eyes..."
    return

label tonks_teacher_event_1_1: #Level 1 Event 1
    m "How were your extra curricular activities today?"
    ton "Ah! It's such a rush!"
    ton "I can't believe how naughty I feel!"
    m "So I take it you managed to sneak a peek?"
    ton "Sort of... I didn't really see it."
    ton "But it was still incredible..."
    ton "Ugh... that look on his face..."
    m "What did you see then?"
    ton "Well, this sweet little Slytherin kid had been staring at my boobs all lesson."
    ton "So, naturally, I get him to stay behind after class."
    ton "I couldn't tell if he was angrier than he was scared..."
    ton "But, as his teacher, I insisted that he write out some lines to correct his behavior."
    m "Do I need to ask what he had to write?"
    ton "\"I will not stare at my teacher's big, beautiful breasts\"..."
    m "Was the big and beautiful part really necessary?"
    ton "Oh, that's not the best bit..."
    ton "I went on to tell him how {b}naughty{/b} it was for him to peek at me..."
    ton "Then I made him pull down his trousers before he wrote his lines."
    m "So you did see it!"
    ton "He still had his underwear on. I think if I pushed him much further he would have snapped."
    ton "Besides, I could still see how hard he was..."
    ton "Ugh... It was crazy..."
    ton "I might have teased him a little more while he wrote them out as well..."
    m "The lines weren't enough?"
    ton "Don't worry, I just whispered in his ear a little..."
    ton "Told him what a naughty boy he'd been..."
    ton "Let him know he'd earn some points for Slytherin..."
    ton "If my boobs happened to rub into his back a little while it happened I don't see how that's my fault."
    m "Ugh... that poor kid."
    ton "Pfft... He was having the time of his life..."
    ton "His underwear was practically {b}soaked{/b} in precum."
    m "Well, do you think he'll spread the word about the favour trading?"
    ton "I'm not sure... Maybe..."
    ton "All I know is that he won't be able to keep his eyes off of me next lesson."
    m "Very good. That'll be all."
    ton "Thank you, Dumbledore."
    ">Tonks turns and leaves, closing the door quietly after her."
    return

label tonks_teacher_event_1_2: #Level 1 Event 2
    m "How were your classes today?"
    ton "Mmmm... Long and hard... Just how I like them..."
    m "I take it you were able to steal a few glances?"
    ton "Mmmm, it was even better than I thought it'd be!"
    ton "Who knew they'd be so nervous!"
    m "What happened?"
    ton "Well, I figured I'd have to be alone with a student to manage to convince them to whip it out..."
    ton "So I gave the cutest little thing I could find detention..."
    ton "Poor boy, I'm not sure he'd ever even been in trouble before."
    ton "So when the bell rang he immediately went on babbling about how sorry he was for speaking in class and how he'd never do it again..."
    ton "Ugh... I had to hold myself back from jumping him right then and there..."
    ton "Anyway, I eventually managed to calm him down and tell him it'll be alright..."
    ton "I even let him know that if he was a good boy he could earn some points for his house."
    m "Did he like the sound of that?"
    ton "You should have seen his eyes light up! He thought it was Christmas!"
    ton "After that it was child's play..."
    ton "Not that he looked like a kid down there... Mmmm, I even had him play with himself for a little bit..."
    ton "Ugh... Fuck, he looked tasty..."
    m "Ahem... So did you pay him his points or just tease him?"
    ton "Don't worry, I made sure \"Ravenclaw\" was paid."
    m "And did he look like the kind to talk?"
    ton "Probably not..."
    m "Well try and get a talker next time. We're trying to build your reputation, remember?"
    ton "I'll try..."
    ton "(Although I might have to play with this one a few more times...)"
    m "That will be all for now, [tonks_name]."
    ton "Thanks, Dumbledore."
    ">With that, Tonks strolls off into the hall."
    return

label tonks_teacher_event_1_3: #Level 1 Event 3
    m "How'd it go?"
    ton "Great! I even managed to convince two boys to show me their dicks at the same time!"
    m "Two at once? Nice."
    ton "Yep. To be honest, they probably would have done it for free."
    ton "Not that they turned down the offer of points though..."
    m "Care to elaborate?"
    ton "Alright then you old perv..."
    ton "Normally I'd just keep the cutest thing that takes my eye back after class for a little one-on-one time..."
    ton "But I actually had to punish these two idiots for real."
    m "What did they do?"
    ton "Ugh... they wouldn't shut up, they kept trying to lift girl's skirts with \"wingardium leviosa\"..."
    ton "They reminded me of my younger self... Which probably meant they were going to far."
    ton "So I kept them after class, gave them the whole lecture about responsibility and respect..."
    m "..."
    ton "Then I told them I'd pay them both ten points to show me their cocks..."
    m "Just like that?"
    ton "Well, there's a lot more subtlety to it in practice..."
    ton "Not that I think I needed it given how horny they were."
    ton "I think the poor buggers actually thought I was going to jerk them both off..."
    ton "Still, I think they had a fun time."
    m "Any chance they'll tell their friends about it?"
    ton "Are you kidding me? The gryffindor common room is probably a buzz already!"
    ton "It wouldn't surprise me if I start getting asked to give boys detention."
    m "Great work."
    ton "Thank you, Dumbledore. That means a lot coming from you."
    m "Even if it is encouragement for seducing your students?"
    ton "Even then."
    ton "Well, I better get back to work, these halls aren't safe unless there's a teacher on patrol."
    m "(I'm not sure they're safe with her on patrol...)"
    return

label tonks_teacher_event_1_4: #Level 1 Event 4
    m "Manage to sneak a peek today?"
    ton "Um... Afraid not..."
    m "Oh."
    ton "But I do have a story for you!"
    m "Well why didn't you just start with that? You had me worried for a moment there!"
    ton "Are you that desperate to hear about me fooling around with my students?"
    m "I'm desperate to hear anything, this office isn't exactly riveting to listen to..."
    ton "In that case, I'll try and add some flair to it."
    ton "Once upon a time-"
    m "Ahem..."
    ton "Too much?"
    m "Just a tad."
    ton "So, I know my job is to try and balance out the favour trading a little..."
    ton "But I just couldn't help myself today..."
    m "Help yourself? You mean..."
    ton "Ugh, I don't normally mess around with girls..."
    ton "(Not since I left here anyway...)"
    ton "But there was the tastiest morsel I have ever seen in class."
    m "..."
    ton "Now, I know when I'm being checked out, I can feel someones eyes on me..."
    ">You nod, unconsciously gazing directly at her tits."
    ton "And most of the time I don't mind... I might even encourage it from time to time..."
    ton "So when I felt a pair of cute little eyes struggling they're hardest not to stare at me."
    ton "I {b}had{/b} to play with her."
    m "Mmmm... what happened?"
    ton "Nothing much... I'm pretty sure she would have freaked if I tried anything..."
    ton "So I just asked her to stay after class for a little... {b}chat{/b}."
    m "What did that chat involve?"
    ton "Not much..."
    ton "I just sat directly in front of her desk..."
    ton "Asked her how she felt she was doing in class..."
    ton "I made sure to ask her if she was feeling distracted..."
    ton "All the while, playing with the buttons on my shirt..."
    ton "Ugh... I've never seen someone so flustered..."
    ton "Eventually, it got too much for her so she just yelled that I was wasting her time and ran off in typical \"slytherin\" fashion."
    m "Do you really think she was looking at you?"
    ton "After that? There's no doubt... she's hooked."
    ton "Now I've just got to reel her in."
    ton "If that's alright with you, sir!"
    m "You're asking my permission?"
    ton "Well, I was only supposed to buy favours from the boys..."
    m "Eat your heart out. Just make sure you keep me in the loop."
    ton "Thanks, Dumbledore."
    ton "I can't believe how much you've mellowed out since I was a student."
    m "Oh, um... time can do that..."
    m "Speaking of, it's getting a bit late..."
    ton "So it is... Night, sir."
    m "Goodnight, Tonks."
    return