label cho_quidd_intro: #have cho come in and talk about wanting help to win more quidditch games against slytherin and gryffindor
    #genie suggest for her to play dirty
    ">With a loud bang, your door is flung open as a disgruntled girl marches in."
    cho "It's not fair!"
    cho "Malfoy's pompous old man just bought the whole \'Slytherin\'' team brand new Nimbus 2018s!"
    cho "\'Ravenclaw\'' can't be expected to win against that!"
    cho "I demand you level the playing field sir!"
    m "Why? Is that crooked as well?"
    cho "This isn't funny sir! With \'Slytherin\' playing dirty there's no way we can win!"
    cho "Ugh! I knew you wouldn't do anything..."
    m "So you don't want to hear my solution then?"
    cho "Wait... You are going to help?!"
    cho "Thank you, thank you, thank you!"
    cho "I take a small size broom and I'd like gold trim with a dark-"
    m "I'm not buying you a broom..."
    m "(Is quidditch like curling then?)"
    cho "Oh..."
    cho "Then what's your solution?"
    m "You said that the \'Slytherin\'s were playing dirty..."
    m "How about you fight fire with fire then?"
    cho "So you think we should fight dirty too?"
    cho "But how? The rules forbid almost all foul play."
    m "Hmmmm..."
    m "What do they say about uniform?"
    cho "Ugh... I don't think there's anything about the uniform in the rule book sir."
    m "So if you intended to wear a skirt while you played-"
    cho "I couldn't do that!"
    cho "Everyone would be able to see straight up it!"
    cho "Not to mention all the other player-"
    cho "Oh..."
    cho "So that's your plan then? For me to distract \'Slytherin\' with some upskirt?"
    m "If you don't think it would work-"
    cho "Of course it would work! Those \'Slytherin\'s are all a bunch of perverts..."
    cho "But I can't go and play a game with a skirt on!"
    cho "All my friends would see!"
    m "They'll forget all about it after you defeat \'Slytherin\'!"
    cho "I really don't think they will..."
    m "Then just tell them it was the only way to win. I'm sure they'll understand."
    cho "You... might be right..."
    cho "But still... I can't do that... can I?"
    m "Miss Granger would..."
    cho "{size=-5}She would?{/size}"
    cho "Alright! I'll do it!"
    cho "Go Go \'Raveclaw\'!"
    m "So when's your next game?"
    cho "I'm actually about to head over for a practice game against \'hufflepuff\' now..."
    m "Sounds like the perfect time to test out your new uniform..."
    cho "Already!"
    cho "Can't we wait a bit longer sir..."
    m "Hmmm... if you don't feel up for it, Miss Granger could prob-"
    cho "Fine..."
    m "Fantastic! Just come back here after the game to tell me how it went!"
    cho "What? Can't I just run back to my dorm?"
    m "Not unless you want the rules to change again..."
    cho "Ugh... Whatever old man..."
    ">With that Cho turns to leave your office."
    m "..."
    m "(I still have no idea what quidditch is...)"
    
    jump day_main_menu




label cho_quidd_1_1: #come back and describe playing with a skirt on (embarrassed)
    ">*knock* *knock* *knock*"
    menu:
        "\"Come in!\"":
            cho "Yes sir..."
        "\"Who is it?\"":
            cho "Cho Chang sir."
            m "Ah miss Chong... Come on in!"
            cho "..."
    ">Cho quickly enters your office, quickly turning her head to make sure she's alone."
    m "You seem a little on edge today..."
    cho "On edge?"
    cho "Of course I'm on edge! I've never felt so humiliated in my life!"
    cho "You had to have me do this on the day half of \"hufflepuff\" shows up to watch the practice didn't you!"
    cho "I bet you were probably in on it..."
    m "Now now, you know I'd never resort to any sort of foul play like that..."
    m "More importantly, how did the game go?"
    m "Score many... points?"
    m "(I hope this stupid game has points...)"
    cho "As a matter of fact I did!"
    cho "{size+=10}150 of them!!!{/size}"
    m "Wow... That seems like a lot!"
    cho "Of course it is, I caught the snitch!"
    m "(The snitch? Is this prison rules?)"
    cho "Today, I was racing after the snitch along with that blockhead Cedric Diggory..."
    cho "I'm normally never fast enough to beat him with my crummy old nimbus 2010..."
    cho "But today I just flew above him as we were both after the snitch!"
    cho "Ah!!! I can't believe I was able to finally catch it!"
    m "Is this the first time you've caught the... snitch?"
    cho "Of course! This is the first game of quidditch \"Ravenclaw\" has won in over six years!"
    m "Wasn't this just a practice game?"
    cho "I was including the practices sir..."
    m "oh..."
    cho "\"Ravenclaw\"... isn't very good..."
    cho "But I have a feeling that's going to change this year!"
    cho "We're a boot in to win the quidditch school cup!"
    m "Wizarding School Cup?"
    cho "Stop being an idiot, Dumbledore!"
    cho "You know what the Q\.S\.C\. is! You've only hosted it for the last 30 years!"
    m "O-of course..."
    cho "Speaking of which you better start getting prepared, it starts in under a month."
    m "I'd be more worried about your team..."
    m "I don't think everyone is going to go down as easily as Cedric Digidy."
    m "Speaking of... What happened to him?"
    cho "Oh... he um... crashed... into some... banisters..."
    m "(Crashed? Is this game a racetrack now?)"
    cho "The nurses said he'll be able to walk again by the end of the week!"
    cho "{size-=1}They're {size-=1}not {size-=1}so {size-=1}sure {size-=1}whether {size-=1}or {size-=1}not {size-=1}he'll {size-=1}wake {size-=1}up {size-=1}though...{/size}"
    m "Anyway, my point is I don't think you'll be able to get away with just a skirt from now on."
    cho "You don't?"
    m "If you want to have any chance of winning this years cup I think you'll need me as a coach."
    cho "Coach?"
    cho "Are you sure you're able to do this sir?"
    m "Look, I gave you one bit of advice and you won your first game in six years."
    m "Imagine what having me coach you for a season could do!"
    cho "OK..."
    cho "But if you want me to keep doing these sorts of things..."
    cho "I want some points!"
    m "Ugh... really?"
    m "(I was hoping she'd forgotten about that...)"
    cho "Yep! If you expect me to come back here and tell you how I've humiliated myself for you then \"Ravenclaw\" should at least reap the benefits."
    m "Fine..."
    m "How many do you want then?"
    cho "How much would Hermione do this for?"
    menu:
        "-20 points-":
            cho "Pffft, she really is a slut..."
            cho "I want 100!"
            m "I don't think so..."
            cho "75!"
            m "30."
            cho "70!"
            m "40."
            cho "60!"
            m "50, final offer."
            cho "Done!"
            $ current_payout = 50
        "-50 points-":
            cho "Done!"
            $ current_payout = 50
        "-100 points-":
            cho "100? Really?"
            cho "Done!"
            m "Wait, would you have done it for less?"
            cho "Too late!"
            $ current_payout = 100
    m "[current_payout] points to \"Gryff-I mean \"Ravenclaw\"!"
    $ Ravenclaw += current_payout
    cho "Thank you sir."
    m "So are you ready for my next bit of coaching advice?"
    cho "Already? Can't I just keep wearing the skirt for now?"
    m "And keep using the same old tactics?"
    m "What sort of coach do you take me for?"
    cho "Well what did you have in mind?"
    m "Seeing as how the skirt was such a success, how about we up the ante then?"
    cho "How do you mean?"
    m "Well that skirt seems a little long to me..."
    m "if you took a few inches off of it the other players probably wouldn't be able to keep their eyes off of you."
    cho "They already couldn't keep their eyes off of me..."
    m "For now... They'll probably get bored of that skirt after a while..."
    cho "They will not!"
    m "Are you going to let me coach you or not?"
    cho "..."
    cho "How much shorter?"
    m "Just a few inches..."
    cho "Alright... I'll get madmam mafkin to make some adjustments..."
    m "Very good. Now when is your next game?"
    cho "In two days. Another practice match, this time against \"Gryffindor\"."
    m "Do you think they'll be distracted by your new skirt?"
    cho "Ha ha ha... if Those \"Gryffindor\" boys lose it over hermione, just imagine what they do when they see me!"
    m "I'm sure you'll win then..."
    cho "So am I. And I'm sure you'll be happy to reward me with a hefty amount of points after the game..."
    m "I look forward to it..."
    ">With that, cho turns and leaves to leave your office."
    m "(I've really gotta learn what this quitit game is...)"
    jump day_main_menu



label cho_quidd_1_2: #come back and describe playing with a shorter skirt on (happy they won)
    ">*knock* *knock* *knock*"
    m "Come in..."
    ">Cho Chang quickly enters your office, a spring in her step."
    m "How did your game go?"
    cho "We won again!"
    cho "I can't believe that we've broken our 6 year dry streak with two back-to-back wins!"
    cho "We could actually win the cup!"
    m "And you weren't embarrassed?"
    cho "I was a little at the start of the game..."
    cho "But once I realized how much it was affecting those slack-jawed \"gryffindor\"s..."
    cho "It was like having my own personal weapon of mass distraction!"
    cho "I don't think Harry even knew where the snitch was most of the time!"
    cho "All he seemed to do was follow me around..."
    cho "{size=-2}Him {size=-2}and {size=-2}half {size=-2}the {size=-2}team...{/size}"
    m "So you're prepared to continue our coaching?"
    cho "As long as we keep winning games, I think it's only reasonable..."
    cho "Speaking of which... did you have any more coaching tips?"
    m "As a matter of fact I do..."
    cho "Good... You can tell me all about them after you pay me my points!"
    m "How does fifty sound?"
    cho "Pfft... Only fifty when my skirt is this short?"
    cho "I want at least sixty..."
    m "Ugh fine..."
    cho "(yes!)"
    m "60 points to \"Ravenclaw\"!"
    $ Ravenclaw += 60
    cho "Thank you sir."
    cho "Now about that tip..."
    m "I've got a tip for you alright... and a bit more-"
    cho "Professor!"
    m "alright, alright... for now, why don't you try shortening that skirt of your again."
    cho "Again? Isn't this short enough?"
    m "Not if you want to win the grand prix or whatever..."
    cho "The quidditch school cup sir..."
    m "Sure..."
    cho "Well I suppose I could take another inch or two off..."
    cho "But we better win the next practice against \"Slytherin\"!"
    m "Hey, the games up to you... All I can give is pointers."
    cho "Hmph... That's not what a coach is supposed to say!"
    cho "You're supposed to believe in me!"
    m "You've gotta show some commitment to the game first."
    cho "commitment..."
    cho "Isn't wearing a skirt enough?"
    m "For now..."
    cho "What's that supposed to mean?"
    m "It means stop being such a prude and shorten that skirt!"
    cho "..."
    cho "fine..."
    cho "Is that all then coach?"
    m "Unless you wanna fool around a little?"
    cho "Not after a game..."
    m "Then that will be all. "
    cho "Alright then coach..."
    ">With that Cho, turns and leaves your office."
    jump day_main_menu

label cho_quidd_1_3: #come back and describe playing without a skirt on (aroused)
    ">*knock* *knock* *knock*"
    m "You can just come in from now on Cho..."
    ">With that, your door slowly opens as Cho enters."
    cho "What if you're in here with that floozy Hermione?"
    cho "I don't want to have to see that!"
    m "Fair enough..."
    m "Now did you manage to win todays game?"
    cho "..."
    cho "No..."
    m "You didn't? Why not?"
    m "Wasn't your skirt distracting enough?"
    cho "It wasn't that..."
    cho "If anything went wrong it's that my skirt was too distracting!"
    m "How's that? Don't you want the other players distracted?"
    cho "I do..."
    cho "But this was too much!"
    cho "I couldn't get them off of me!"
    cho "Half the \"slytherin\" team spent the whole game following me around, trying to get a peak from underneath!"    
    m "Hmmm, I was worried this might happen...."
    cho "Well how are you going to fix it then coach?"
    m "I think we'll need to change our angle of attack..."
    cho "Our angle?"
    m "At the moment panty shot that all the boys are hoping for can only be seen from underneath-"
    m "-so as a result, most of the boys are hounding you to get a look."
    m "But if we widen our angle of attack, they won't be forced to chase you to get a look..."
    cho "Widen our angle? What do you mean?"
    m "You're gonna have to loose the jacket..."
    m "Probably the sweater as well if we're being honest..."
    cho "You want me to take my jacket off?"
    cho "I'll freeze!"
    cho "Not to mention the other players and the spectators will be able to see everything!"
    cho "My skirt was at least a little hidden before..."
    m "If you want to win this is the only way..."
    cho "Can't I just go back to the longer skirt? That was working!"
    m "I don't think these \"slytherin\" boys are going to be interested in that after what they saw today..."
    m "I know I wouldn't..."
    cho "Coach!"
    m "Just trust me... If you lose the next game you can put it back on..."
    cho "OK... but I want some points!"
    cho "Seventy five to be precise..."
    m "...fine..."
    cho "(awesome!)"
    m "75 points to \"Ravenclaw\"!"
    $ Ravenclaw += 75
    cho "Alright... well I'll come and see you after the next game..."
    cho "When I'm not wearing a jacket..."
    m "And wearing a mini-skirt..."
    cho "And wearing... a mini-skirt..."
    m "Good. With tactics like this we can't lose."
    cho "We better not!"
    cho "This might be the first real chance \"Ravenclaw\" has ever had to win the cup."
    m "I'm sure this must mean a lot to you..."
    cho "It does... I might even get picked up by a pro team!"
    m "..."
    cho "Agh, I can't wait!"
    cho "I better go talk to the team!"
    m "Well, off you go then."
    cho "Thank you Professor..."
    ">Cho cheerily leaves your office."

    jump day_main_menu





















